# Generated by Django 3.1.1 on 2020-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='font_size',
        ),
        migrations.AddField(
            model_name='snippet',
            name='fontsize',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
